export const DISHES_LOADING='DISHES_LOADING';
export const ADD_DISHES='ADD_DISHES';
export const DISHES_FAILED='DISHES_FAILED';
export const ADD_COMMENTS='ADD_COMMENTS';
export const COMMENTS_FAILED='COMMENTS_FAILED';
